### ISSUE TITLE
Need to change the SSM Paramater type in the template

### ISSUE THREAD

**Issue by plample** [aws-quickstart/quickstart-nextflow#6]
The biotech Blueprint quickstart creates SSM parameters as String.
The Nextflow quickstart template expect strong type.
Need to replace all 'SSM:Parameter...' by String in bb.nextflow.template

ex:  
```
VpcId:
    Description: 'The ID of your existing VPC (e.g., vpc-0343606e) to use for the Nextflow environment.'
    Type: **'AWS::SSM::Parameter::Value<String>'**
    Default: /BB/Networking/VPC/Research
```

becomes
 ```
 VpcId:
    Description: 'The ID of your existing VPC (e.g., vpc-0343606e) to use for the Nextflow environment.'
    Type: **String**
    Default: /BB/Networking/VPC/Research
```
